Item.create(name: "ball", size: 8, picture: "https://s3.us-east-2.amazonaws.com/r3-village/items/ball.png")
Item.create(name: "bear", size: 8, picture: "https://s3.us-east-2.amazonaws.com/r3-village/items/bear.png")
Item.create(name: "cube", size: 8, picture: "https://s3.us-east-2.amazonaws.com/r3-village/items/cube.png")
Item.create(name: "egame", size: 8, picture: "https://s3.us-east-2.amazonaws.com/r3-village/items/egame.png")
Item.create(name: "robot", size: 8, picture: "https://s3.us-east-2.amazonaws.com/r3-village/items/robot.png")
Item.create(name: "xylophone", size: 8, picture: "https://s3.us-east-2.amazonaws.com/r3-village/items/xylophone.png")
Ingredient.create(name: "bottle", picture: "https://s3.us-east-2.amazonaws.com/r3-village/ingredients/bottle.png")
Ingredient.create(name: "cardboard", picture: "https://s3.us-east-2.amazonaws.com/r3-village/ingredients/cardboard.png")
Ingredient.create(name: "ewaste", picture: "https://s3.us-east-2.amazonaws.com/r3-village/ingredients/ewaste.png")
Ingredient.create(name: "food", picture: "https://s3.us-east-2.amazonaws.com/r3-village/ingredients/food.png")
Ingredient.create(name: "plastic", picture: "https://s3.us-east-2.amazonaws.com/r3-village/ingredients/plastic.png")
Ingredient.create(name: "waste", picture: "https://s3.us-east-2.amazonaws.com/r3-village/ingredients/waste.png")